Repository forkdelta/tokenbase, pull requests merged in 2018-03, with the labels that each got.

#340 Fix common test issues
  .travis.yml
  scripts/test.py
Labels: enhancement

#243 Add OTCBTC (OTB) Token
  tokens/0xa86a0da9d05d0771955df05b44ca120661af16de.yaml
Labels: information complete

#377 Fix CS / CREDITS credits.com ticker discrepancy
  tokens/0x12a35383ca24ceb44cdcbbecbeb7baccb5f3754a.yaml
  tokens/0x46b9ad944d1059450da1163511069c718f699d31.yaml
Labels: listing update

#262 Add SocialX (SOCX) Token
  tokens/0x587c549c4113127340ac0f5e996cab7a4f35bb49.yaml
Labels: information complete

#297 Listing request - Engraved Coin (XEG)
  tokens/0x85a7c57a4068280dd1166089a18acf35b4ba11e2.yaml
Labels: information complete

#371 List EU coin (EC)
  tokens/0x40caa728bb4bafa56f38a58623a12fbe6c90209d.yaml
Labels: information complete

#445 Update LCWP website address
  tokens/0xe8fc7e1973496848fcb486c5bb880f68487ea0bb.yaml
Labels: listing update

#398 Updated Quantum Resistant Ledger Token Info
  tokens/0x697beac28b09e122c4332d163985e8a73121b97f.yaml
Labels: information complete

#378 List PAL
  tokens/0x562952c749d05dca4cd004489a153c7ee7e58240.yaml
  tokens/0xf923ba61b43161a83afe2cab7d77ea1e41f27918.yaml
Labels: information complete

#505 CashBagCoin Listing Request
  tokens/0xf444cd92e09cc8b2a23cd2eecb3c1e4cc8da6958.yaml
Labels: information complete

#332 Updated the contract details of LOVE Token
  tokens/0xb510788cbb9aea54221d3dc8cce2dff629a1dbf7.yaml
  tokens/0xe6eFd46EB6CDd73A7fe1e760Fa0c25a299755a4B.yaml
Labels: information complete

#800 Enable no-response bot
  .github/no-response.yml
Labels: enhancement
